{
  imports = [
    ./hyprland
    ./waybar
    ./pycharm
    ./wlogout
    ./stylix.nix
    ./fish.nix
    ./alacritty.nix
    ./desktopEntries.nix
    ./nemo.nix
    ./gpu-screen-recorder-ui.nix
    ./discord.nix
    ./rofi.nix
    ./git.nix
    ./fonts.nix
    ./soundcard.nix
    ./screenshots.nix
    ./mako.nix
    ./starship.nix
    ./librewolf.nix
    ./lutris.nix
    ./catppuccin.nix
    ./mpris-proxy.nix
    ./easyeffects.nix
    ./udiskie.nix
    ];
}
