{
  imports = [
    ./nvidia.nix
    ./bluetooth.nix
    ./boot.nix
    ./audio.nix
    ./autologin.nix
    ./fish.nix
    ./gvfs.nix
    ./hyprland.nix
    ./nix.nix
    ./nixpkgs.nix
    ./nvidia.nix
    ./polkit.nix
    ./time.nix
    ./amnezia-vpn.nix
    ./printers.nix
    ./nix-ld.nix
    ./udev.nix
    ./gnome-disks.nix
    ./postgres.nix
    ./kernel.nix
    ./nh.nix
  ];
}
